version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    volumes:
      - ./api:/app
    environment:
      - PORT=8080
      - GO_ENV=development
      - DB_USER=root
      - DB_NAME=go_graph_real_api_dev
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306
      - TEST_DB_NAME=go_graph_real_api_test
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - AUTH0_DOMAIN=dev-go_graph_real_api-proto.jp.auth0.com
      - AUTH0_AUDIENCE=http://localhost:8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  redis:
    build:
      context: ./redis/docker
    ports:
      - "6379:6379"
  mysql:
    build:
      context: ./mysql/docker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql:delegated
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      # - MYSQL_DATABASE=go_graph_real_api_dev
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64 #for m1Tip

  # operator:
  #   build:
  #     context: .
  #     dockerfile: ./go_graph_real_api-operator-proto/Dockerfile.dev
  #   volumes:
  #     - ./go_graph_real_api-operator-proto:/app
  #   ports:
  #     - "8090:3000"

volumes:
  mysql_db:
    driver: local
